site_name: 噗叽
site_url: https://puji.danling.org
site_author: Open Science Lab
site_description: 噗叽--浦科实验室的创意入门手册。一键启动科学探索之旅，激发无限创新可能!
copyright: All rights reserved &copy; 2024-Present, Shanghai Artificial Intelligence Laboratory

repo_name: PuJi
repo_url: https://github.com/MultiMolecule/puji

nav:
  - 噗叽: index.md
  - 基础知识:
      - index: basics/index.md
      - 使用Linux服务器: basics/linux.md
      - 使用Conda管理环境: basics/conda.md
      - 使用Slurm作业调度系统: basics/slurm.md
      - 数据管理与传输: basics/data.md
  - 实验室服务器介绍:
      - index: server_details/index.md
      - S集群: server_details/pjS.md
      - 北京超算A100: server_details/blscN32HA14P.md
      - 北京超算4090: server_details/blscN40R4PJ.md
      - CPU单机: server_details/pjcpu.md
  - 最佳实践指南:
      - index: best_practices/index.md
      - 开发环境配置: best_practices/develop.md
      - 数据传输: best_practices/data_transfer.md
      - 训练任务提交: best_practices/submit.md
  - 附录: appendix.md
  - 关于:
      - about/index.md
      - 许可证: about/license.md
      - 隐私声明: about/privacy.md

theme:
  name: material
  custom_dir: overrides
  language: "zh"
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  logo: "assets/images/logo.png"
  favicon: "assets/images/logo.ico"
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  font: false

extra:
  analytics:
    provider: google
    property: "G-RE7EKZ9T8D"
  consent:
    title: Cookie Consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better. Please check out our
      <a href="https://zyc.ai/about/privacy">Privacy Policy</a> for more information.
  generator: false
  manifest: "manifest.webmanifest"

extra_css:
  - assets/css/fonts.css
  - assets/css/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/shortcuts.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - mdx_math
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialy.gemoji
      emoji_generator: !!python/name:materialy.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - smarty
  - tables
  - toc:
      permalink: true

plugins:
  - git-committers
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            parameter_headings: true
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
          import:
            - https://docs.python.org/3/objects.inv
            - https://pytorch.org/docs/stable/objects.inv
            - https://huggingface.co/docs/transformers/master/en/objects.inv
            - https://danling.org/objects.inv
            - https://chanfig.danling.org/objects.inv
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - locale: zh
          build: true
          default: true
          name: 汉语
        - locale: en
          build: true
          default: false
          name: English
      reconfigure_material: true
      reconfigure_search: true
  - git-revision-date-localized:
      type: iso_datetime
  - rss:
      match_path: .*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - search:
      separator: '[\s\u200b\-]'
  - tags
  # - typeset
